# Generated by Django 3.2 on 2022-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeLatest', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoTitle',
            field=models.CharField(max_length=150),
        ),
    ]
