# Generated by Django 3.2 on 2022-08-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeLatest', '0003_alter_video_videotitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='videoId',
            field=models.ForeignKey(db_column='videoId', on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='youtubeLatest.video'),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together={('videoId', 'type')},
        ),
    ]
